# Generated by Django 4.2.6 on 2023-10-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(default=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('home_goals', models.PositiveIntegerField(default=0)),
                ('away_goals', models.PositiveIntegerField(default=0)),
                ('is_played', models.BooleanField(default=False)),
                ('is_reprogrammed', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('GANO_LOCAL', 'Ganó Local'), ('GANO_VISITANTE', 'Ganó Visitante'), ('EMPATE', 'Empate')], max_length=30, null=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('role', models.CharField(choices=[('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo'), ('CAS', 'CAS'), ('RxH', 'Recibo por Honorarios')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('departament_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.departamentcollege')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('is_validated', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_in', to='championship.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_out', to='championship.player')),
            ],
        ),
        migrations.CreateModel(
            name='Reprogramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.match')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_away', to='championship.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.edition'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_home', to='championship.team'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.team')),
            ],
        ),
        migrations.CreateModel(
            name='Expulsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('is_validated', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.player')),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_as_player', to='championship.player')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_as_team', to='championship.player')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('AMARILLA', 'Amarilla'), ('ROJA', 'Roja')], max_length=10)),
                ('minute', models.PositiveIntegerField()),
                ('is_validated', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.player')),
            ],
        ),
    ]
