# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='edition',
            new_name='Edition',
        ),
    ]
