# Generated by Django 4.2.6 on 2023-11-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_rename_edition_match_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Edition',
            new_name='edition',
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Orden de la fase en el campeonato')),
                ('type', models.CharField(choices=[('GROUP_STAGE', 'Fase de grupos'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final'), ('OTHER', 'Otro')], default='GROUP_STAGE', help_text='Tipo de fase', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(help_text='Orden del grupo dentro de la fase')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.phase')),
                ('teams', models.ManyToManyField(to='championship.team')),
            ],
        ),
    ]
