# Generated by Django 4.2.6 on 2023-11-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_alter_departamentcollege_is_active_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
